### ISSUE TITLE
"local_address":"0.0.0.0",

### ISSUE THREAD

**Issue by cattyhouse** [bazingaterry/CHN_ROUTER_VPN#1]
这么设置好吗，这样的话等于是在服务器上开了一个socks5公开代理，任何人都能用。。。
不如写成 "local_address":"127.0.0.1",

**Comment by kamingchan** [comment]
- 是的，会有安全隐患，目前可以通过修改默认端口，加上禁止端口扫描来避免，如果有更好的方法请提出。
- 设置为`"local_address":"0.0.0.0"`的原因是要转发来自VPN的TCP流量，若设置为`"local_address":"127.0.0.1"`则只能本机使用。

**Comment by cattyhouse** [comment]
设置为 "local_address":"127.0.0.1" 不会只是本机使用，因为你已经用iptables把所有PREROUTING的流量转发到127.0.0.1:1080端口上去了，所以不会有问题。

**Comment by kamingchan** [comment]
不是的，可能你把 iptables 的 INPUT OUTPUT 和 PREROUTING 搞混了，使用 PREROUTING 的话， TCP 流量是没有进入本机的，只是路由功能，类似的可以想象是路由器的样子，或是参见下图。
![](http://vbird.dic.ksu.edu.tw/linux_server/0250simple_firewall_files/iptables_04.gif)
