### ISSUE TITLE
想问下centos6.5执行脚本到此处就停止了，怎样操作呢？

### ISSUE THREAD

**Issue by kankankankankankan** [bazingaterry/CHN_ROUTER_VPN#2]
![e e vxq5vr c0 4jrms m](https://cloud.githubusercontent.com/assets/11487346/9978976/f1bc51e4-5f84-11e5-82f7-222304a9ac7e.png)
对脚本不太懂，感谢大大帮忙了

**Comment by kamingchan** [comment]
不好意思，这是一个Bug，已在新版本修复，谢谢关注！

**Comment by kankankankankankan** [comment]
好的 谢谢大大！
