### ISSUE TITLE
Azure中国CentOS6上执行，认不出这是CentOS

### ISSUE THREAD

**Issue by missdeer** [bazingaterry/CHN_ROUTER_VPN#3]
RT

**Comment by kamingchan** [comment]
不好意思，没有条件测试，你可以直接修改脚本，跳过系统版本检测。

**Comment by hop9527** [comment]
你好  请教下在国内服务器和国外服务器上都运行这一个脚本吗

**Comment by kamingchan** [comment]
不是，这个是国内服务器运行的脚本，国外的只需要一个 Shadowsock Server。

**Comment by hop9527** [comment]
哦  谢谢回复，您还没休息啊   可以加下您的QQ请教下吗

**Comment by hop9527** [comment]
![2](https://cloud.githubusercontent.com/assets/3134350/13534662/48465c70-e271-11e5-9f2f-16736f0c8106.jpg)
我是用GRE隧道 不是shadows连接国内外服务器的，但是route这里我这配上好不通，麻烦帮忙看看，我会尽自己的努力去报答感谢你的。

**Comment by kamingchan** [comment]
对 GRE 隧道不熟悉，抱歉。

但按你图上的意思，只需要在 PC 连上 VPN 服务器就可以。

**Comment by hop9527** [comment]
这个vpn服务器和出口服务器您那里是用shadowsock连接的  gre和他原理是一样，并且更加简单，也不会有干扰，现在都弄好了，就只有路由和iptables转发没写对了，不知道您什么时候有空能帮我看看iptables，iptables我不怎么熟悉

**Comment by kamingchan** [comment]
如果 GRE 和 ss-redir 原理一样，那就肯定会监听 0.0.0.0 的某个端口，然后你参照  `iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 1080` 这一句，把 1080 改成对应的端口即可。

**Comment by hop9527** [comment]
哦  我明白差异了，你这是用iptables转发，我是用路由转发。谢谢你，早点休息哦，我再试试
