### ISSUE TITLE
centos 运行脚本报错line345-359

### ISSUE THREAD

**Issue by kankankankankankan** [bazingaterry/CHN_ROUTER_VPN#4]
ca.pem [auto create[0m]
auto create ca.pem ...
install.sh: line 337: ipsec: command not found
ca.cert.pem [[33;1mauto create[0m]
auto create ca.cert.pem ...
install.sh: line 345: ipsec: command not found
install.sh: line 353: ipsec: command not found
install.sh: line 354: ipsec: command not found
install.sh: line 354: ipsec: command not found
install.sh: line 358: ipsec: command not found
install.sh: line 359: ipsec: command not found
install.sh: line 359: ipsec: command not found
configure the pkcs12 cert password(Can be empty):

**Comment by kamingchan** [comment]
新版本的小bug，暂时不影响使用，我会在国庆之后修复。

**Comment by kankankankankankan** [comment]
好的，大大，节日快乐
