### ISSUE TITLE
Azure中国的Ubuntu上执行sudo应该取消

### ISSUE THREAD

**Issue by 1oca1h0st** [bazingaterry/CHN_ROUTER_VPN#5]
Azure中国的Ubuntu 14.04LTS上，hostname带“-”，脚本运行到673行，报错出现sudo unable resolve hostname，建议脚本要求root权限，去掉sudo开头，直接用root权限增加防火墙

**Comment by kamingchan** [comment]
脚步会检测是否有root权限，没有不会运行。
Azure的用户多次反应这个问题了，但手头上暂时没有资源，我有时间会解决。

**Comment by 1oca1h0st** [comment]
我手头有多余的资源，若需要可以给我发邮件创建一台用于测试:)

我测试去掉sudo选项后运行成功:)
