### ISSUE TITLE
上不去油管脸书等等，是否是DNS污染？

### ISSUE THREAD

**Issue by maonickbob** [bazingaterry/CHN_ROUTER_VPN#8]
VPS配置完了以后能翻墙，国内走国内VPS，国外走的国外的VPS，但是上不去谷歌，油管，脸书什么的，但是如果我上e绅士、youporn的话，因为我这个是韩国服务器，这些网站会被墙，所以可以确定我流量走国外VPS去了，玩游戏通过这个也稳定，但是就是上不去这些被DNS污染的网站！？我改过DNS为谷歌的两个DNS解析。`curl www.google.com` 是 `the document has been moved`，`curl www.google.co.kr`就会等很长时间，然后curl[52]错误，`empty reply from server`.结论是DNS污染？还是我的配置问题？如果是DNS污染的话可以用chinadns解决么？顺便说下我的国内VPS是腾讯云。。。哦，对了，gmail、inbox什么的能够上去，好奇怪！

**Comment by kamingchan** [comment]
可以使用 `dig www.google.co.kr` 看看 IP 是什么，我这里查询是有污染的。如果使用 53 端口查询需要使用 TCP 方式，或者使用 OpenDNS 的 443 端口。ChinaDNS 可以解决污染，Gmail inbox 能够上去的原因是它们并没有被 DNS 污染，只是 IP 封锁。
