### ISSUE TITLE
ss安装错误

### ISSUE THREAD

**Issue by xzpjerry** [bazingaterry/CHN_ROUTER_VPN#9]
环境：centos 6.5 x64 腾讯云
上个月装还是可以的，估计是ss那个自动安装脚本前几天更新了引起的错误，下面是错误信息：
···
。。。。。。
make[2]: Leaving directory `/root/shadowsocks-libev-master/src'
Making all in doc
make[2]: Entering directory`/root/shadowsocks-libev-master/doc'
  GEN      shadowsocks-libev.xml
/bin/sh: asciidoc: command not found
make[2]: **\* [shadowsocks-libev.xml] Error 127
make[2]: Leaving directory `/root/shadowsocks-libev-master/doc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/root/shadowsocks-libev-master'
make: **\* [all] Error 2

Shadowsocks-libev install failed!
···

**Comment by xzpjerry** [comment]
试了下ubuntu 14.04 也是一样的错误

make[2]: Leaving directory `/home/ubuntu/shadowsocks-libev-master/src'
Making all in doc
make[2]: Entering directory`/home/ubuntu/shadowsocks-libev-master/doc'
  GEN      shadowsocks-libev.xml
/bin/bash: asciidoc: command not found
make[2]: **\* [shadowsocks-libev.xml] Error 127
make[2]: Leaving directory `/home/ubuntu/shadowsocks-libev-master/doc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/ubuntu/shadowsocks-libev-master'
make: **\* [all] Error 2

Shadowsocks-libev install failed!

**Comment by kamingchan** [comment]
好的，暂时改用 2.4.7 版本。

**Comment by xzpjerry** [comment]
有一个地方还有问题，install.sh里 搜关键词'install_ss_libev_CentOS' ,229行的cd shadowsocks-libev-master，要改成cd shadowsocks-libev-2.4.7

**Comment by kamingchan** [comment]
好的，忽略了，已修复。
